version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: authentificationgo_bd
    restart: no
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authentificationgo
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:latest
    container_name: authentificationgo_test_db
    restart: no
    environment:
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_secret
      POSTGRES_DB: authentificationgo_test
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
