name: Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: up database
        run: docker-compose up -d

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.24.1"

      - name: Run tests
        run: go test -v ./tests
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build  -t go-auth:latest .

      - name: Tag docker image
        run: docker tag go-auth:latest ${{ secrets.DOCKER_USERNAME }}/go-auth-api:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/go-auth-api:latest
